name: Julien Demare
favicon: null
layout_spectrum: 0.75759
typography_spectrum: 0.75112
title: Julien Demare - E-Commerce and Payments Specialist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-48816933-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#00bcd6'
    - '#5f7d8c'
    - '#ff9900'
    - '#ec1261'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
