typography_spectrum: 0.5471295486204326
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.551070042187348
  lightness: 0.7610492296516895
  saturation: 0.8355616079643369
  rhythmicContrast: 0.2846023659221828
opengraph:
  image: null
  type: null
  appId: '722925851180963'
layout_spectrum: 0.6642110191751271
analytics:
  google: UA-48816933-2
  facebook: null
  twitter: null
author:
  name: Julien Demare
  url: 'http://julien-demare.com/'
logo: null
name: Julien Demare
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: LinkedIn
    url: 'http://www.linkedin.com/in/juliendemare'
    type: external
  - name: Twitter
    url: 'https://www.twitter.com/juliendemare'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cbdf75e2-fccf-4789-a747-769150c85b7e.ico
title: E-Commerce addict!
description: E-Commerce addict!
purpose: []
