name: Julien Demare
favicon: null
layout_spectrum: 0.67209
typography_spectrum: 0.81577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#28282a'
    - '#d6d6d6'
    - '#49474a'
    - '#777578'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
