name: Julien Demare
favicon: null
layout_spectrum: 0.74545
typography_spectrum: 0.50188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00bc9c'
    - '#2b3e51'
    - '#9c55b8'
    - '#f2c500'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
